grpc:
  connect_timeout: 15
  connection_timeout: 15
  keepalive_inactive_ping_time_trigger: 0
  keepalive_inactive_ping_timeout: 0
  keepalive_max_conn_age: 0
  keepalive_max_conn_age_grace: 0
  keepalive_max_conn_idle: 0
  keepalive_min_wait: 0
  keepalive_permit_without_stream: false
  max_concurrent_streams: 0
  max_recv_msg_size: 0
  max_send_msg_size: 0
  num_stream_workers: 0
  read_buffer_size: 0
  write_buffer_size: 0
  x509_cert_file: ""
  x509_key_file: ""
instance:
  initial_unhealthy: true
  instance_id: ""
  instance_port: 0
  instance_prefix: ams-
  instance_timeout: 5
  instance_version: v0.0.1
  internal_health_frequency: 1
namespace:
  ns_id:
  ns_name:
service:
  sv_id:
  sv_name:
service_auto_create:
  sac_dns_routing: multivalue
  sac_dns_ttl: 90
  sac_dns_type: srv
  sac_health_custom: true
  sac_health_failthreshold: 1
  sac_health_pubdns_path: ""
  sac_health_pubdns_type: ""
target:
  app_name: connector.service
  region: us-east-1
