notifier_gateway:
  # required, valid aws region to host dynamodb services
  dynamodb_aws_region: us-east-1
  # optional, dynamodb uses dax or not
  dynamodb_use_dax: false
  # conditional, if dax = true, dax url is required
  dynamodb_dax_url: ""
  # required, dynamodb table name, used for server routing by notifier gateway
  dynamodb_table: ""
  # optional, dynamodb action timeout seconds
  dynamodb_timeout_seconds: 5
  # optional, dynamodb action retries count
  dynamodb_action_retries: 3
  # optional, self-signed server ca pem file path
  server_ca_cert:
  # optional, gateway secret key phrase, used for hashing or other validation purposes
  gateway_key:
  # optional, service discovery action timeout seconds
  service_discovery_timeout_seconds: 5
  # optional, health report service record clean up frequency seconds, default is 120, minmimum is 30, maximum is 3600 (1 hour), 0 = 120
  health_report_cleanup_frequency_seconds: 120
  # optional, health report service record stale minutes, total minutes before record is considered stale and primed for clean up removal
  # minimum = 3 minutes, default = 5 minutes, maximum = 15 minutes, 0 = 5 minutes
  health_report_record_stale_minutes: 5
  # optional, list of hash key name and secrets for use by this host
  hash_keys:
    - hash_key_name: ""
      hash_key_secret: ""